spring:
  application:
    name: "project-web-application"
  sql:
    init:
      mode: always
      platform: postgres
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/booking
    username: postgres
    password: "${Password}"
